"""Added balance and balance_updated_at field to account table

Revision ID: 55fa655a9c60
Revises: 0cc9918de006
Create Date: 2025-05-18 00:33:03.312068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fa655a9c60'
down_revision: Union[str, None] = '0cc9918de006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance', sa.Numeric(), nullable=False))
    op.add_column('accounts', sa.Column('balance_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'balance_updated_at')
    op.drop_column('accounts', 'balance')
    # ### end Alembic commands ###
