"""Fixed spelling error for field in BankRequisition

Revision ID: edd25ab5d63f
Revises: 8aacd9e755fc
Create Date: 2025-05-14 21:07:47.582118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd25ab5d63f'
down_revision: Union[str, None] = '8aacd9e755fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_requisitions', sa.Column('reference', sa.String(), nullable=True))
    op.drop_column('bank_requisitions', 'referebce')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_requisitions', sa.Column('referebce', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bank_requisitions', 'reference')
    # ### end Alembic commands ###
